-- Phase 2 reproducible baseline for a fresh database.
-- This file is intentionally additive and idempotent. It closes the gap
-- between the original schema.sql and the DGP application contract without
-- fabricating the missing historical production migrations.
--
-- Run after schema.sql. It creates the complete Phase-2 table contract and
-- the core DGP scoring/ranking objects required by the application. Existing
-- production migrations remain the authoritative history for already-live DBs.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typnamespace = 'public'::regnamespace AND typname = 'app_role') THEN
    CREATE TYPE public.app_role AS ENUM ('PLAYER','ADMIN','SUPER_ADMIN');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.seasons (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text UNIQUE NOT NULL,
  name text NOT NULL,
  system_type text NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  is_active boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.player_memberships (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id integer NOT NULL REFERENCES public.players(id) ON DELETE CASCADE,
  season_id bigint NOT NULL REFERENCES public.seasons(id) ON DELETE CASCADE,
  is_member boolean NOT NULL DEFAULT false,
  valid_from date,
  valid_to date,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.user_profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  player_id integer REFERENCES public.profiles(id) ON DELETE SET NULL,
  display_name text,
  role public.app_role NOT NULL DEFAULT 'PLAYER',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.players ADD COLUMN IF NOT EXISTS birth_year integer;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS fide_id text;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

ALTER TABLE public.tournaments ADD COLUMN IF NOT EXISTS season_id bigint REFERENCES public.seasons(id) ON DELETE SET NULL;
ALTER TABLE public.tournaments ADD COLUMN IF NOT EXISTS tournament_type text;
ALTER TABLE public.tournaments ADD COLUMN IF NOT EXISTS tournament_level text;
ALTER TABLE public.tournaments ADD COLUMN IF NOT EXISTS tournament_scope text NOT NULL DEFAULT 'GENERAL';
ALTER TABLE public.tournaments ADD COLUMN IF NOT EXISTS category_code text;
ALTER TABLE public.tournaments ADD COLUMN IF NOT EXISTS event_stage text NOT NULL DEFAULT 'REGULAR';
ALTER TABLE public.tournaments ADD COLUMN IF NOT EXISTS access_type text NOT NULL DEFAULT 'OPEN';
ALTER TABLE public.tournaments ADD COLUMN IF NOT EXISTS start_date date;
ALTER TABLE public.tournaments ADD COLUMN IF NOT EXISTS end_date date;
ALTER TABLE public.tournaments ADD COLUMN IF NOT EXISTS registration_deadline timestamptz;
ALTER TABLE public.tournaments ADD COLUMN IF NOT EXISTS max_players integer;
ALTER TABLE public.tournaments ADD COLUMN IF NOT EXISTS rounds integer;
ALTER TABLE public.tournaments ADD COLUMN IF NOT EXISTS fide_rated boolean NOT NULL DEFAULT false;
ALTER TABLE public.tournaments ADD COLUMN IF NOT EXISTS published boolean NOT NULL DEFAULT false;
ALTER TABLE public.tournaments ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

CREATE TABLE IF NOT EXISTS public.tournament_results (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tournament_id integer NOT NULL REFERENCES public.tournaments(id) ON DELETE CASCADE,
  player_id integer NOT NULL REFERENCES public.players(id) ON DELETE CASCADE,
  final_rank integer,
  score numeric,
  games_played integer,
  wins integer NOT NULL DEFAULT 0,
  draws integer NOT NULL DEFAULT 0,
  losses integer NOT NULL DEFAULT 0,
  rating_standard integer,
  rating_rapid integer,
  rating_blitz integer,
  rating_used integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  points_awarded numeric NOT NULL DEFAULT 0,
  scoring_rule_id bigint,
  calculated_at timestamptz,
  UNIQUE (tournament_id, player_id)
);

ALTER TABLE public.tournament_registrations ADD COLUMN IF NOT EXISTS player_id integer REFERENCES public.players(id) ON DELETE SET NULL;
ALTER TABLE public.tournament_registrations ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'REGISTERED';
ALTER TABLE public.tournament_registrations ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.tournament_registrations ALTER COLUMN email DROP NOT NULL;

CREATE TABLE IF NOT EXISTS public.scoring_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.seasons(id) ON DELETE CASCADE,
  rule_code text NOT NULL,
  rule_name text NOT NULL,
  system_type text NOT NULL CHECK (system_type IN ('ACADEMY','DUBROVNIK_GP')),
  version text NOT NULL,
  valid_from date NOT NULL,
  valid_to date,
  formula_type text NOT NULL CHECK (formula_type IN ('ACADEMY_POSITION','DUBROVNIK_FACTORS')),
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.scoring_rule_parameters (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scoring_rule_id bigint NOT NULL REFERENCES public.scoring_rules(id) ON DELETE CASCADE,
  parameter_code text NOT NULL,
  parameter_name text NOT NULL,
  parameter_value numeric,
  parameter_text text,
  min_value numeric,
  max_value numeric,
  description text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (scoring_rule_id, parameter_code)
);

CREATE TABLE IF NOT EXISTS public.scoring_position_points (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scoring_rule_id bigint NOT NULL REFERENCES public.scoring_rules(id) ON DELETE CASCADE,
  event_stage text NOT NULL CHECK (event_stage IN ('QUALIFICATION','FINAL')),
  position integer NOT NULL,
  points numeric NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (scoring_rule_id,event_stage,position)
);

CREATE TABLE IF NOT EXISTS public.scoring_factor_values (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scoring_rule_id bigint NOT NULL REFERENCES public.scoring_rules(id) ON DELETE CASCADE,
  factor_code text NOT NULL,
  factor_key text NOT NULL,
  factor_label text,
  factor_value numeric NOT NULL,
  min_value numeric,
  max_value numeric,
  description text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.scoring_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scoring_rule_id bigint NOT NULL REFERENCES public.scoring_rules(id) ON DELETE CASCADE,
  category_code text NOT NULL,
  category_name text NOT NULL,
  category_type text NOT NULL CHECK (category_type IN ('GENERAL','SPECIAL_CATEGORY')),
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (scoring_rule_id,category_code)
);

CREATE TABLE IF NOT EXISTS public.scoring_category_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scoring_category_id bigint NOT NULL REFERENCES public.scoring_categories(id) ON DELETE CASCADE,
  rule_type text NOT NULL CHECK (rule_type IN ('AGE_MAX','AGE_MIN','RATING_MAX','RATING_MIN','MEMBERSHIP_REQUIRED','CUSTOM')),
  parameter_code text NOT NULL,
  parameter_value numeric,
  parameter_text text,
  description text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.scoring_category_sources (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scoring_category_id bigint NOT NULL REFERENCES public.scoring_categories(id) ON DELETE CASCADE,
  source_type text NOT NULL CHECK (source_type IN ('GENERAL_GP','CATEGORY_SPECIAL')),
  source_category_code text,
  is_required boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.grand_prix_final_qualifiers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.seasons(id) ON DELETE CASCADE,
  final_tournament_id integer NOT NULL REFERENCES public.tournaments(id) ON DELETE CASCADE,
  player_id integer NOT NULL REFERENCES public.players(id) ON DELETE CASCADE,
  qualification_rank integer NOT NULL CHECK (qualification_rank > 0),
  qualification_points numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'QUALIFIED' CHECK (status IN ('QUALIFIED','INVITED','CONFIRMED','DECLINED','REPLACEMENT','PLAYED','NO_SHOW')),
  replaced_player_id integer REFERENCES public.players(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  final_slot integer,
  source_rank integer,
  UNIQUE (final_tournament_id,player_id)
);

CREATE TABLE IF NOT EXISTS public.junior_gp_final_qualifiers (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.seasons(id) ON DELETE CASCADE,
  final_tournament_id integer NOT NULL REFERENCES public.tournaments(id) ON DELETE CASCADE,
  player_id integer NOT NULL REFERENCES public.players(id) ON DELETE CASCADE,
  qualification_rank integer NOT NULL,
  qualification_points numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'QUALIFIED' CHECK (status IN ('QUALIFIED','INVITED','CONFIRMED','DECLINED','REPLACEMENT','PLAYED','NO_SHOW')),
  replaced_player_id integer REFERENCES public.players(id) ON DELETE SET NULL,
  final_slot integer,
  source_rank integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (final_tournament_id,player_id)
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='tournament_results_scoring_rule_id_fkey') THEN
    ALTER TABLE public.tournament_results ADD CONSTRAINT tournament_results_scoring_rule_id_fkey FOREIGN KEY (scoring_rule_id) REFERENCES public.scoring_rules(id) ON DELETE SET NULL;
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.player_is_dgp_member_on_date(p_player_id integer, p_on_date date)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $$
  SELECT COALESCE(
    (SELECT pm.is_member FROM public.player_memberships pm JOIN public.seasons s ON s.id=pm.season_id
      WHERE pm.player_id=p_player_id AND p_on_date BETWEEN COALESCE(pm.valid_from,s.start_date) AND COALESCE(pm.valid_to,s.end_date)
      ORDER BY pm.id DESC LIMIT 1),
    (SELECT p.is_member FROM public.players p WHERE p.id=p_player_id), false);
$$;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_profiles up WHERE up.id=auth.uid() AND up.role::text IN ('ADMIN','SUPER_ADMIN'));
$$;

CREATE OR REPLACE FUNCTION public.is_super_admin()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_profiles up WHERE up.id=auth.uid() AND up.role::text='SUPER_ADMIN');
$$;

CREATE OR REPLACE FUNCTION public.require_dgp_admin()
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE v_role text;
BEGIN
  SELECT upper(up.role::text) INTO v_role FROM public.user_profiles up WHERE up.id=auth.uid();
  IF coalesce(v_role,'') NOT IN ('ADMIN','SUPER_ADMIN') THEN
    RAISE EXCEPTION 'Nedozvoljena radnja: samo administrator može izvršiti ovu radnju.';
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.calculate_dgp_points(p_tournament_id integer)
RETURNS TABLE(player_id integer, final_rank integer, points_awarded numeric)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE v_scoring_rule_id bigint; v_tournament_level text; v_tempo text; v_n integer; v_avg_rating numeric; v_fn numeric; v_fr numeric; v_fc numeric; v_ft numeric; v_total_factor numeric;
BEGIN
  PERFORM public.require_dgp_admin();
  SELECT sr.id INTO v_scoring_rule_id FROM public.scoring_rules sr WHERE sr.rule_code='DGP_2027' AND sr.system_type='DUBROVNIK_GP' AND sr.is_active=true LIMIT 1;
  IF v_scoring_rule_id IS NULL THEN RAISE EXCEPTION 'Aktivno DGP scoring pravilo nije pronađeno.'; END IF;
  SELECT upper(coalesce(t.tournament_level,'CLUB')), upper(coalesce(t.tempo,'STANDARD')) INTO v_tournament_level,v_tempo FROM public.tournaments t WHERE t.id=p_tournament_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Turnir % ne postoji.',p_tournament_id; END IF;
  SELECT count(*) INTO v_n FROM public.tournament_results tr WHERE tr.tournament_id=p_tournament_id AND coalesce(tr.games_played,0)>0;
  IF v_n < 6 THEN
    UPDATE public.tournament_results SET points_awarded=0, scoring_rule_id=v_scoring_rule_id, calculated_at=now(), updated_at=now() WHERE tournament_id=p_tournament_id;
    RETURN QUERY SELECT tr.player_id,tr.final_rank,0::numeric FROM public.tournament_results tr WHERE tr.tournament_id=p_tournament_id ORDER BY tr.final_rank NULLS LAST; RETURN;
  END IF;
  SELECT avg(coalesce(tr.rating_used,1400)) INTO v_avg_rating FROM public.tournament_results tr WHERE tr.tournament_id=p_tournament_id AND coalesce(tr.games_played,0)>0;
  v_fn := round(least(1.50,0.80+0.16*log(2,v_n::numeric/7.0)),3);
  v_fr := round(greatest(0.80,least(1.30,1.00+(v_avg_rating-1750)*0.0008)),3);
  v_fc := case v_tournament_level when 'CLUB' then 1.00 when 'COMPETITIVE' then 1.25 when 'TOP' then 1.50 else 1.00 end;
  v_ft := case v_tempo when 'STANDARD' then 1.00 when 'RAPID' then 0.90 when 'BLITZ' then 0.75 else 1.00 end;
  v_total_factor := least(2.50,v_fn*v_fr*v_fc*v_ft);
  UPDATE public.tournament_results tr SET points_awarded=case when coalesce(tr.games_played,0)<=0 or tr.final_rank is null then 0 else greatest(1,least(250,round(100*power(((v_n-tr.final_rank+1)::numeric/v_n::numeric),1.35)*v_total_factor))) end, scoring_rule_id=v_scoring_rule_id, calculated_at=now(), updated_at=now() WHERE tr.tournament_id=p_tournament_id;
  RETURN QUERY SELECT tr.player_id,tr.final_rank,tr.points_awarded FROM public.tournament_results tr WHERE tr.tournament_id=p_tournament_id ORDER BY tr.final_rank NULLS LAST;
END;
$$;

CREATE OR REPLACE FUNCTION public.update_dgp_result(p_result_id bigint,p_final_rank integer,p_score numeric,p_games_played integer,p_wins integer,p_draws integer,p_losses integer)
RETURNS public.tournament_results LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE v_row public.tournament_results;
BEGIN
  PERFORM public.require_dgp_admin();
  IF p_final_rank IS NOT NULL AND p_final_rank<1 THEN RAISE EXCEPTION 'Konačni rang mora biti pozitivan broj.'; END IF;
  IF p_score IS NOT NULL AND p_score<0 THEN RAISE EXCEPTION 'Rezultat (score) ne može biti negativan.'; END IF;
  IF coalesce(p_games_played,0)<0 OR coalesce(p_wins,0)<0 OR coalesce(p_draws,0)<0 OR coalesce(p_losses,0)<0 THEN RAISE EXCEPTION 'Broj partija, pobjeda, remija i poraza ne može biti negativan.'; END IF;
  UPDATE public.tournament_results SET final_rank=p_final_rank,score=p_score,games_played=p_games_played,wins=coalesce(p_wins,0),draws=coalesce(p_draws,0),losses=coalesce(p_losses,0),updated_at=now() WHERE id=p_result_id RETURNING * INTO v_row;
  IF NOT FOUND THEN RAISE EXCEPTION 'Rezultat % ne postoji.',p_result_id; END IF;
  PERFORM public.calculate_dgp_points(v_row.tournament_id);
  SELECT * INTO v_row FROM public.tournament_results WHERE id=p_result_id;
  RETURN v_row;
END;
$$;

CREATE OR REPLACE VIEW public.dgp_general_ranking AS
WITH quota AS (
  SELECT greatest(5,ceil(count(*)::numeric/2.0)::integer) quota FROM public.tournaments t JOIN public.seasons s ON s.id=t.season_id WHERE s.code='DGP-2027' AND t.tournament_scope='GENERAL' AND t.event_stage='REGULAR'
), regular_rows AS (
  SELECT tr.player_id,tr.points_awarded,tr.final_rank,tr.tournament_id,row_number() over(partition by tr.player_id order by tr.points_awarded desc,tr.final_rank,tr.tournament_id) rn
  FROM public.tournament_results tr JOIN public.tournaments t ON t.id=tr.tournament_id JOIN public.seasons s ON s.id=t.season_id
  WHERE s.code='DGP-2027' AND t.tournament_scope='GENERAL' AND t.event_stage='REGULAR' AND tr.games_played>0 AND tr.points_awarded>0
), regular_agg AS (
  SELECT rr.player_id,sum(rr.points_awarded) filter(where rr.rn<=q.quota) regular_points,count(*) filter(where rr.rn<=q.quota) counted_regular
  FROM regular_rows rr CROSS JOIN quota q GROUP BY rr.player_id,q.quota
), finals AS (
  SELECT tr.player_id,sum(tr.points_awarded) final_points FROM public.tournament_results tr JOIN public.tournaments t ON t.id=tr.tournament_id JOIN public.seasons s ON s.id=t.season_id
  WHERE s.code='DGP-2027' AND t.tournament_scope='GENERAL' AND t.event_stage='FINAL' AND tr.games_played>0 AND tr.points_awarded>0 GROUP BY tr.player_id
)
SELECT p.id player_id,p.full_name,(coalesce(r.regular_points,0)+coalesce(f.final_points,0)) general_gp_points,
coalesce(r.counted_regular,0)+case when coalesce(f.final_points,0)>0 then 1 else 0 end counted_results,coalesce(f.final_points,0) final_points
FROM public.players p LEFT JOIN regular_agg r ON r.player_id=p.id LEFT JOIN finals f ON f.player_id=p.id WHERE p.is_active=true;

CREATE OR REPLACE VIEW public.dgp_results_entry AS
SELECT tr.id,tr.tournament_id,t.name tournament_name,tr.player_id,p.full_name,tr.final_rank,tr.score,tr.games_played,tr.wins,tr.draws,tr.losses,
tr.rating_standard,tr.rating_rapid,tr.rating_blitz,tr.rating_used,tr.points_awarded,tr.calculated_at
FROM public.tournament_results tr JOIN public.tournaments t ON t.id=tr.tournament_id JOIN public.players p ON p.id=tr.player_id JOIN public.seasons s ON s.id=t.season_id WHERE s.code='DGP-2027';

ALTER TABLE public.seasons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tournament_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scoring_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scoring_rule_parameters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scoring_position_points ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scoring_factor_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scoring_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scoring_category_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scoring_category_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.grand_prix_final_qualifiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.junior_gp_final_qualifiers ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON public.seasons, public.tournament_results, public.grand_prix_final_qualifiers, public.junior_gp_final_qualifiers TO authenticated;
GRANT SELECT ON public.dgp_general_ranking, public.dgp_results_entry TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_dgp_points(integer), public.update_dgp_result(bigint,integer,numeric,integer,integer,integer,integer) TO authenticated;

-- Indexes needed for the Phase-2 foreign-key workload.
CREATE INDEX IF NOT EXISTS idx_gp_final_qualifiers_replaced_player ON public.grand_prix_final_qualifiers(replaced_player_id);
CREATE INDEX IF NOT EXISTS idx_junior_final_qualifiers_player ON public.junior_gp_final_qualifiers(player_id);
CREATE INDEX IF NOT EXISTS idx_junior_final_qualifiers_replaced_player ON public.junior_gp_final_qualifiers(replaced_player_id);
CREATE INDEX IF NOT EXISTS idx_junior_final_qualifiers_season ON public.junior_gp_final_qualifiers(season_id);
CREATE INDEX IF NOT EXISTS idx_page_content_page ON public.page_content(page_id);
CREATE INDEX IF NOT EXISTS idx_player_memberships_season ON public.player_memberships(season_id);
CREATE INDEX IF NOT EXISTS idx_tournament_registrations_player ON public.tournament_registrations(player_id);
CREATE INDEX IF NOT EXISTS idx_tournaments_season ON public.tournaments(season_id);
CREATE INDEX IF NOT EXISTS idx_user_profiles_player ON public.user_profiles(player_id);
