import PublicHeader from './components/PublicHeader';
import { supabase } from '../lib/supabaseClient';

export const revalidate = 30;
export const metadata = { title: 'ŠK Dubrovnik Grand Prix', description: 'Službeni javni portal Šahovskog kluba Dubrovnik — turniri, prijave, ljestvice, rezultati i vijesti.' };

export default async function HomePage() {
  const [{ data: tournaments }, { data: news }] = await Promise.all([
    supabase.from('tournaments').select('*').eq('published', true).order('starts_at', { ascending: true }).limit(6),
    supabase.from('news').select('*').order('published_at', { ascending: false }).limit(3),
  ]);
  return <><PublicHeader active="/" /><section className="home-hero"><div className="home-hero-inner"><div><span className="eyebrow">Šahovski klub Dubrovnik</span><h1>Šah koji traje.<br /><em>Grand Prix</em> koji povezuje.</h1><p>Turniri, prijave, rezultati i ljestvice na jednom mjestu. Pratite sezonu ŠK Dubrovnik i uključite se u natjecanje.</p><div className="hero-actions"><a className="btn-primary" href="/turniri">Pogledaj turnire</a><a className="btn-ghost" href="/poredak">Otvori ljestvice</a></div></div><div className="hero-stat"><span>Dubrovnik Grand Prix</span><strong>2026 / 27</strong><small>Nova sezona. Novi potez.</small></div></div></section><div className="board-row">{Array.from({ length: 16 }).map((_, i) => <span key={i}></span>)}</div><main className="public-main"><section className="feature-grid"><article className="feature-card feature-dark"><span className="section-kicker">Natjecanje</span><h2>Prijavi se i igraj.</h2><p>Odaberi turnir, provjeri uvjete i pošalji prijavu online.</p><a href="/prijave">Prijave →</a></article><article className="feature-card"><span className="section-kicker">Grand Prix</span><h2>Prati svoj plasman.</h2><p>Opći GP i kategorijske ljestvice prate napredak kroz sezonu.</p><a href="/poredak">Ljestvice →</a></article><article className="feature-card"><span className="section-kicker">Rezultati</span><h2>Svaki rezultat je važan.</h2><p>Pregled završenih i objavljenih turnira na jednom mjestu.</p><a href="/rezultati">Rezultati →</a></article></section><section className="home-section"><div className="section-heading"><div><span className="section-kicker">Kalendar</span><h2>Najave turnira</h2></div><a href="/turniri">Svi turniri →</a></div><div className="home-list">{!tournaments?.length ? <div className="public-card"><p>Trenutačno nema objavljenih turnira.</p></div> : tournaments.map(t => <a className="event-row" href={`/turniri/${t.id}`} key={t.id}><span>{t.starts_at ? new Date(t.starts_at).toLocaleDateString('hr-HR') : '—'}</span><strong>{t.name}</strong><b>→</b></a>)}</div></section><section className="home-section"><div className="section-heading"><div><span className="section-kicker">Aktualno</span><h2>Vijesti</h2></div><a href="/vijesti">Sve vijesti →</a></div><div className="news-grid">{!news?.length ? <div className="public-card"><p>Još nema objavljenih vijesti.</p></div> : news.map(item => <article className="public-card news-public" key={item.id}>{item.tag && <span className="section-kicker">{item.tag}</span>}<h3>{item.title}</h3>{item.excerpt && <p>{item.excerpt}</p>}</article>)}</div></section></main><footer>© {new Date().getFullYear()} ŠK Dubrovnik Grand Prix · Šahovski klub Dubrovnik</footer></>;
}
