-- Dubrovnik Grand Prix
-- FAZA 2.1: players + rating history + seasonal membership + seasons
-- Namjerno NE dira postojeću public.profiles legacy/test tablicu.

create table if not exists public.seasons (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  season_start date not null,
  season_end date not null,
  system_type text not null check (system_type in ('ACADEMY', 'DUBROVNIK_GP')),
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  constraint seasons_dates_valid check (season_end >= season_start)
);

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  birth_year integer not null check (birth_year between 1900 and extract(year from current_date)::integer),
  fide_id bigint unique,
  title text,
  category text,
  is_sk_dubrovnik_member boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.player_ratings (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  rating_date date not null,
  standard_rating integer,
  rapid_rating integer,
  blitz_rating integer,
  created_at timestamptz not null default now(),
  constraint player_ratings_at_least_one_rating check (
    standard_rating is not null or rapid_rating is not null or blitz_rating is not null
  ),
  constraint player_ratings_unique_month unique (player_id, rating_date)
);

create table if not exists public.player_memberships (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  season_id bigint not null references public.seasons(id) on delete cascade,
  is_member boolean not null default true,
  valid_from date,
  valid_to date,
  created_at timestamptz not null default now(),
  constraint player_memberships_unique unique (player_id, season_id),
  constraint player_memberships_dates_valid check (
    valid_to is null or valid_from is null or valid_to >= valid_from
  )
);

-- Optional link: a registered Auth user can be linked to one player.
alter table public.user_profiles
  add column if not exists player_id bigint references public.players(id) on delete set null;

create unique index if not exists user_profiles_player_id_unique
  on public.user_profiles(player_id)
  where player_id is not null;

create index if not exists player_ratings_player_date_idx
  on public.player_ratings(player_id, rating_date desc);

create index if not exists player_memberships_season_idx
  on public.player_memberships(season_id, player_id);

-- RLS
alter table public.seasons enable row level security;
alter table public.players enable row level security;
alter table public.player_ratings enable row level security;
alter table public.player_memberships enable row level security;

-- Public read: these are public-facing sports data.
drop policy if exists "Public can read seasons" on public.seasons;
create policy "Public can read seasons"
on public.seasons for select
using (true);

drop policy if exists "Public can read active players" on public.players;
create policy "Public can read active players"
on public.players for select
using (active = true);

drop policy if exists "Public can read player ratings" on public.player_ratings;
create policy "Public can read player ratings"
on public.player_ratings for select
using (true);

drop policy if exists "Public can read player memberships" on public.player_memberships;
create policy "Public can read player memberships"
on public.player_memberships for select
using (true);

-- Admin write access.
drop policy if exists "Admins can manage seasons" on public.seasons;
create policy "Admins can manage seasons"
on public.seasons for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can manage players" on public.players;
create policy "Admins can manage players"
on public.players for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can manage player ratings" on public.player_ratings;
create policy "Admins can manage player ratings"
on public.player_ratings for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can manage player memberships" on public.player_memberships;
create policy "Admins can manage player memberships"
on public.player_memberships for all to authenticated
using (public.is_admin()) with check (public.is_admin());

-- Initial seasons requested for the project.
insert into public.seasons (code, name, season_start, season_end, system_type, is_active)
values
  ('ACADEMY-2026-27', 'GP Akademije 2026/27', '2026-09-01', '2027-08-31', 'ACADEMY', true),
  ('DGP-2027', 'Dubrovnik Grand Prix 2027', '2027-01-01', '2027-12-31', 'DUBROVNIK_GP', false)
on conflict (code) do nothing;
