-- ŠK Dubrovnik Grand Prix — Phase 2 DGP bootstrap
-- Run after schema.sql on a fresh Supabase database.
-- This migration creates the Phase 2 DGP schema required by the admin UI,
-- scoring engine, rankings and Final qualification workflow.

create type public.app_role as enum ('PLAYER', 'ADMIN', 'SUPER_ADMIN');

create table if not exists public.seasons (
  id bigint generated by default as identity primary key,
  code text unique not null,
  name text not null,
  system_type text not null,
  start_date date not null,
  end_date date not null,
  is_active boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.player_memberships (
  id bigint generated by default as identity primary key,
  player_id integer not null references public.players(id) on delete cascade,
  season_id bigint not null references public.seasons(id) on delete cascade,
  is_member boolean not null default false,
  valid_from date,
  valid_to date,
  created_at timestamptz not null default now()
);

create table if not exists public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  player_id integer references public.profiles(id) on delete set null,
  display_name text,
  role public.app_role not null default 'PLAYER',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.players add column if not exists birth_year integer;
alter table public.players add column if not exists fide_id text;
alter table public.players add column if not exists is_active boolean not null default true;
alter table public.players add column if not exists updated_at timestamptz not null default now();

alter table public.tournaments add column if not exists season_id bigint references public.seasons(id) on delete set null;
alter table public.tournaments add column if not exists tournament_type text;
alter table public.tournaments add column if not exists tournament_level text;
alter table public.tournaments add column if not exists tournament_scope text not null default 'GENERAL';
alter table public.tournaments add column if not exists category_code text;
alter table public.tournaments add column if not exists event_stage text not null default 'REGULAR';
alter table public.tournaments add column if not exists access_type text not null default 'OPEN';
alter table public.tournaments add column if not exists start_date date;
alter table public.tournaments add column if not exists end_date date;
alter table public.tournaments add column if not exists registration_deadline timestamptz;
alter table public.tournaments add column if not exists max_players integer;
alter table public.tournaments add column if not exists rounds integer;
alter table public.tournaments add column if not exists fide_rated boolean not null default false;
alter table public.tournaments add column if not exists published boolean not null default false;
alter table public.tournaments add column if not exists updated_at timestamptz not null default now();

create table if not exists public.tournament_results (
  id bigint generated by default as identity primary key,
  tournament_id integer not null references public.tournaments(id) on delete cascade,
  player_id integer not null references public.players(id) on delete cascade,
  final_rank integer,
  score numeric,
  games_played integer,
  wins integer not null default 0,
  draws integer not null default 0,
  losses integer not null default 0,
  rating_standard integer,
  rating_rapid integer,
  rating_blitz integer,
  rating_used integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  points_awarded numeric not null default 0,
  scoring_rule_id bigint,
  calculated_at timestamptz,
  unique (tournament_id, player_id)
);

alter table public.tournament_registrations add column if not exists player_id integer references public.players(id) on delete set null;
alter table public.tournament_registrations add column if not exists status text not null default 'REGISTERED';
alter table public.tournament_registrations add column if not exists updated_at timestamptz not null default now();

create table if not exists public.scoring_rules (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons(id) on delete cascade,
  rule_code text not null,
  rule_name text not null,
  system_type text not null check (system_type in ('ACADEMY','DUBROVNIK_GP')),
  version text not null,
  valid_from date not null,
  valid_to date,
  formula_type text not null check (formula_type in ('ACADEMY_POSITION','DUBROVNIK_FACTORS')),
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.scoring_rule_parameters (
  id bigint generated by default as identity primary key,
  scoring_rule_id bigint not null references public.scoring_rules(id) on delete cascade,
  parameter_code text not null,
  parameter_name text not null,
  parameter_value numeric,
  parameter_text text,
  min_value numeric,
  max_value numeric,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (scoring_rule_id, parameter_code)
);

create table if not exists public.scoring_position_points (
  id bigint generated by default as identity primary key,
  scoring_rule_id bigint not null references public.scoring_rules(id) on delete cascade,
  event_stage text not null check (event_stage in ('QUALIFICATION','FINAL')),
  position integer not null,
  points numeric not null,
  created_at timestamptz not null default now(),
  unique (scoring_rule_id,event_stage,position)
);

create table if not exists public.scoring_factor_values (
  id bigint generated by default as identity primary key,
  scoring_rule_id bigint not null references public.scoring_rules(id) on delete cascade,
  factor_code text not null,
  factor_key text not null,
  factor_label text,
  factor_value numeric not null,
  min_value numeric,
  max_value numeric,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.scoring_categories (
  id bigint generated by default as identity primary key,
  scoring_rule_id bigint not null references public.scoring_rules(id) on delete cascade,
  category_code text not null,
  category_name text not null,
  category_type text not null check (category_type in ('GENERAL','SPECIAL_CATEGORY')),
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (scoring_rule_id,category_code)
);

create table if not exists public.scoring_category_rules (
  id bigint generated by default as identity primary key,
  scoring_category_id bigint not null references public.scoring_categories(id) on delete cascade,
  rule_type text not null check (rule_type in ('AGE_MAX','AGE_MIN','RATING_MAX','RATING_MIN','MEMBERSHIP_REQUIRED','CUSTOM')),
  parameter_code text not null,
  parameter_value numeric,
  parameter_text text,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.scoring_category_sources (
  id bigint generated by default as identity primary key,
  scoring_category_id bigint not null references public.scoring_categories(id) on delete cascade,
  source_type text not null check (source_type in ('GENERAL_GP','CATEGORY_SPECIAL')),
  source_category_code text,
  is_required boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.grand_prix_final_qualifiers (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons(id) on delete cascade,
  final_tournament_id integer not null references public.tournaments(id) on delete cascade,
  player_id integer not null references public.players(id) on delete cascade,
  qualification_rank integer not null check (qualification_rank > 0),
  qualification_points numeric not null default 0,
  status text not null default 'QUALIFIED' check (status in ('QUALIFIED','INVITED','CONFIRMED','DECLINED','REPLACEMENT','PLAYED','NO_SHOW')),
  replaced_player_id integer references public.players(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  final_slot integer,
  source_rank integer,
  unique (final_tournament_id,player_id)
);

create table if not exists public.junior_gp_final_qualifiers (
  id bigint generated always as identity primary key,
  season_id bigint not null references public.seasons(id) on delete cascade,
  final_tournament_id integer not null references public.tournaments(id) on delete cascade,
  player_id integer not null references public.players(id) on delete cascade,
  qualification_rank integer not null,
  qualification_points numeric not null default 0,
  status text not null default 'QUALIFIED' check (status in ('QUALIFIED','INVITED','CONFIRMED','DECLINED','REPLACEMENT','PLAYED','NO_SHOW')),
  replaced_player_id integer references public.players(id) on delete set null,
  final_slot integer,
  source_rank integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (final_tournament_id,player_id)
);

alter table public.tournament_results add constraint tournament_results_scoring_rule_id_fkey
  foreign key (scoring_rule_id) references public.scoring_rules(id) on delete set null;

create or replace function public.player_is_dgp_member_on_date(p_player_id integer, p_on_date date)
returns boolean language sql stable security definer set search_path = '' as $$
  select coalesce(
    (select pm.is_member
       from public.player_memberships pm
      join public.seasons s on s.id=pm.season_id
      where pm.player_id=p_player_id
        and p_on_date between coalesce(pm.valid_from,s.start_date) and coalesce(pm.valid_to,s.end_date)
      order by pm.id desc limit 1),
    (select p.is_member from public.players p where p.id=p_player_id), false
  );
$$;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.user_profiles up where up.id=auth.uid() and up.role::text in ('ADMIN','SUPER_ADMIN'));
$$;

create or replace function public.is_super_admin()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.user_profiles up where up.id=auth.uid() and up.role::text='SUPER_ADMIN');
$$;

create or replace function public.require_dgp_admin()
returns void language plpgsql security definer set search_path = '' as $$
declare v_role text;
begin
  select upper(up.role::text) into v_role from public.user_profiles up where up.id=auth.uid();
  if coalesce(v_role,'') not in ('ADMIN','SUPER_ADMIN') then
    raise exception 'Nedozvoljena radnja: samo administrator može izvršiti ovu radnju.';
  end if;
end;
$$;

create or replace function public.calculate_dgp_points(p_tournament_id integer)
returns table(player_id integer, final_rank integer, points_awarded numeric)
language plpgsql security definer set search_path = '' as $$
declare v_scoring_rule_id bigint; v_tournament_level text; v_tempo text; v_n integer; v_avg_rating numeric; v_fn numeric; v_fr numeric; v_fc numeric; v_ft numeric; v_total_factor numeric;
begin
  perform public.require_dgp_admin();
  select sr.id into v_scoring_rule_id from public.scoring_rules sr where sr.rule_code='DGP_2027' and sr.system_type='DUBROVNIK_GP' and sr.is_active=true limit 1;
  if v_scoring_rule_id is null then raise exception 'Aktivno DGP scoring pravilo nije pronađeno.'; end if;
  select upper(coalesce(t.tournament_level,'CLUB')), upper(coalesce(t.tempo,'STANDARD')) into v_tournament_level,v_tempo from public.tournaments t where t.id=p_tournament_id;
  if not found then raise exception 'Turnir % ne postoji.',p_tournament_id; end if;
  select count(*) into v_n from public.tournament_results tr where tr.tournament_id=p_tournament_id and coalesce(tr.games_played,0)>0;
  if v_n < 6 then
    update public.tournament_results set points_awarded=0, scoring_rule_id=v_scoring_rule_id, calculated_at=now(), updated_at=now() where tournament_id=p_tournament_id;
    return query select tr.player_id,tr.final_rank,0::numeric from public.tournament_results tr where tr.tournament_id=p_tournament_id order by tr.final_rank nulls last; return;
  end if;
  select avg(coalesce(tr.rating_used,1400)) into v_avg_rating from public.tournament_results tr where tr.tournament_id=p_tournament_id and coalesce(tr.games_played,0)>0;
  v_fn := round(least(1.50,0.80+0.16*log(2,v_n::numeric/7.0)),3);
  v_fr := round(greatest(0.80,least(1.30,1.00+(v_avg_rating-1750)*0.0008)),3);
  v_fc := case v_tournament_level when 'CLUB' then 1.00 when 'COMPETITIVE' then 1.25 when 'TOP' then 1.50 else 1.00 end;
  v_ft := case v_tempo when 'STANDARD' then 1.00 when 'RAPID' then 0.90 when 'BLITZ' then 0.75 else 1.00 end;
  v_total_factor := least(2.50,v_fn*v_fr*v_fc*v_ft);
  update public.tournament_results tr set points_awarded=case when coalesce(tr.games_played,0)<=0 or tr.final_rank is null then 0 else greatest(1,least(250,round(100*power(((v_n-tr.final_rank+1)::numeric/v_n::numeric),1.35)*v_total_factor))) end, scoring_rule_id=v_scoring_rule_id, calculated_at=now(), updated_at=now() where tr.tournament_id=p_tournament_id;
  return query select tr.player_id,tr.final_rank,tr.points_awarded from public.tournament_results tr where tr.tournament_id=p_tournament_id order by tr.final_rank nulls last;
end;
$$;

create or replace function public.update_dgp_result(p_result_id bigint,p_final_rank integer,p_score numeric,p_games_played integer,p_wins integer,p_draws integer,p_losses integer)
returns public.tournament_results language plpgsql security definer set search_path = '' as $$
declare v_row public.tournament_results;
begin
  perform public.require_dgp_admin();
  if p_final_rank is not null and p_final_rank<1 then raise exception 'Konačni rang mora biti pozitivan broj.'; end if;
  if p_score is not null and p_score<0 then raise exception 'Rezultat (score) ne može biti negativan.'; end if;
  if coalesce(p_games_played,0)<0 or coalesce(p_wins,0)<0 or coalesce(p_draws,0)<0 or coalesce(p_losses,0)<0 then raise exception 'Broj partija, pobjeda, remija i poraza ne može biti negativan.'; end if;
  update public.tournament_results set final_rank=p_final_rank,score=p_score,games_played=p_games_played,wins=coalesce(p_wins,0),draws=coalesce(p_draws,0),losses=coalesce(p_losses,0),updated_at=now() where id=p_result_id returning * into v_row;
  if not found then raise exception 'Rezultat % ne postoji.',p_result_id; end if;
  perform public.calculate_dgp_points(v_row.tournament_id);
  select * into v_row from public.tournament_results where id=p_result_id;
  return v_row;
end;
$$;

create or replace view public.dgp_general_ranking as
with quota as (
  select greatest(5,ceil(count(*)::numeric/2.0)::integer) quota
  from public.tournaments t join public.seasons s on s.id=t.season_id
  where s.code='DGP-2027' and t.tournament_scope='GENERAL' and t.event_stage='REGULAR'
), regular_rows as (
  select tr.player_id,tr.points_awarded,tr.final_rank,tr.tournament_id,
         row_number() over(partition by tr.player_id order by tr.points_awarded desc,tr.final_rank,tr.tournament_id) rn
  from public.tournament_results tr join public.tournaments t on t.id=tr.tournament_id join public.seasons s on s.id=t.season_id
  where s.code='DGP-2027' and t.tournament_scope='GENERAL' and t.event_stage='REGULAR' and tr.games_played>0 and tr.points_awarded>0
), regular_agg as (
  select rr.player_id,sum(rr.points_awarded) filter(where rr.rn<=q.quota) regular_points,
         array_agg(rr.points_awarded order by rr.points_awarded desc,rr.final_rank,rr.tournament_id) filter(where rr.rn<=q.quota) regular_tiebreak,
         count(*) filter(where rr.rn<=q.quota) counted_regular
  from regular_rows rr cross join quota q group by rr.player_id,q.quota
), finals as (
  select tr.player_id,sum(tr.points_awarded) final_points,
         array_agg(tr.points_awarded order by tr.points_awarded desc,tr.final_rank,tr.tournament_id) final_tiebreak
  from public.tournament_results tr join public.tournaments t on t.id=tr.tournament_id join public.seasons s on s.id=t.season_id
  where s.code='DGP-2027' and t.tournament_scope='GENERAL' and t.event_stage='FINAL' and tr.games_played>0 and tr.points_awarded>0 group by tr.player_id
)
select p.id player_id,p.full_name,(coalesce(r.regular_points,0)+coalesce(f.final_points,0)) general_gp_points,
       coalesce(r.counted_regular,0)+case when coalesce(f.final_points,0)>0 then 1 else 0 end counted_results,
       coalesce(r.regular_tiebreak,array[]::numeric[])||coalesce(f.final_tiebreak,array[]::numeric[]) regular_tiebreak,
       coalesce(f.final_points,0) final_points
from public.players p left join regular_agg r on r.player_id=p.id left join finals f on f.player_id=p.id where p.is_active=true;

create or replace view public.dgp_category_ranking as
with categories as (select category_code from public.scoring_categories where category_type='SPECIAL_CATEGORY' and is_active=true),
eligible as (
 select c.category_code,tr.player_id,tr.tournament_id,tr.points_awarded,tr.final_rank,
        row_number() over(partition by c.category_code,tr.player_id order by tr.points_awarded desc,tr.final_rank,tr.tournament_id) rn
 from categories c join public.tournament_results tr on true join public.tournaments t on t.id=tr.tournament_id join public.seasons s on s.id=t.season_id
 join public.players p on p.id=tr.player_id
 where s.code='DGP-2027' and t.event_stage='REGULAR' and tr.games_played>0 and tr.points_awarded>0 and p.is_active=true
   and ((c.category_code='WOMEN' and p.gender in ('F','Ž','FEMALE')) or (c.category_code='U20' and 2027-p.birth_year<=20) or (c.category_code='U16' and 2027-p.birth_year<=16) or (c.category_code='U12' and 2027-p.birth_year<=12) or (c.category_code='S50' and 2027-p.birth_year>=50) or (c.category_code='S65' and 2027-p.birth_year>=65) or (c.category_code='U1800' and coalesce(tr.rating_used,tr.rating_rapid,tr.rating_standard,tr.rating_blitz)<1800))
), counted as (
 select e.*,greatest(5,ceil(count(*) over(partition by e.category_code)::numeric/2.0)::integer) quota from eligible e
), agg as (
 select category_code,player_id,sum(points_awarded) filter(where rn<=quota) category_special_points,count(*) filter(where rn<=quota) counted_special_results,max(quota) quota,
        array_agg(points_awarded order by points_awarded desc) filter(where rn<=quota) special_tiebreak from counted group by category_code,player_id
)
select a.category_code,a.player_id,p.full_name,coalesce(g.general_gp_points,0)+coalesce(a.category_special_points,0) category_gp_points,
       coalesce(g.general_gp_points,0) general_gp_points,coalesce(a.category_special_points,0) category_special_points,a.counted_special_results,
       a.quota,a.special_tiebreak,0::numeric eligible_final_points
from agg a join public.players p on p.id=a.player_id left join public.dgp_general_ranking g on g.player_id=a.player_id;

create or replace view public.dgp_s50_ranking as
select player_id,full_name,general_gp_points,
       greatest(0,category_gp_points-general_gp_points) s50_special_points,
       category_gp_points s50_total_points,counted_special_results counted_s50_results,
       special_tiebreak s50_tiebreak from public.dgp_category_ranking where category_code='S50';
create or replace view public.dgp_s65_ranking as
select player_id,full_name,general_gp_points,greatest(0,category_gp_points-general_gp_points) s65_special_points,
       category_gp_points s65_total_points,counted_special_results counted_s65_results,special_tiebreak s65_tiebreak from public.dgp_category_ranking where category_code='S65';
create or replace view public.dgp_u1800_ranking as
select player_id,full_name,general_gp_points,greatest(0,category_gp_points-general_gp_points) u1800_special_points,
       category_gp_points u1800_total_points,counted_special_results counted_u1800_results,special_tiebreak u1800_tiebreak from public.dgp_category_ranking where category_code='U1800';
create or replace view public.dgp_u20_ranking as
select player_id,full_name,general_gp_points,greatest(0,category_gp_points-general_gp_points) u20_special_points,
       category_gp_points u20_total_points,counted_special_results counted_u20_results,special_tiebreak u20_tiebreak from public.dgp_category_ranking where category_code='U20';
create or replace view public.dgp_u16_ranking as
select player_id,full_name,general_gp_points,greatest(0,category_gp_points-general_gp_points) u16_special_points,
       category_gp_points u16_total_points,counted_special_results counted_u16_results,special_tiebreak u16_tiebreak from public.dgp_category_ranking where category_code='U16';
create or replace view public.dgp_u12_ranking as
select player_id,full_name,general_gp_points,greatest(0,category_gp_points-general_gp_points) u12_special_points,
       category_gp_points u12_total_points,counted_special_results counted_u12_results,special_tiebreak u12_tiebreak from public.dgp_category_ranking where category_code='U12';
create or replace view public.dgp_women_ranking as
select player_id,full_name,general_gp_points,greatest(0,category_gp_points-general_gp_points) women_special_points,
       category_gp_points women_total_points,counted_special_results counted_women_results,special_tiebreak women_tiebreak from public.dgp_category_ranking where category_code='WOMEN';

create or replace view public.dgp_results_entry as
select tr.id,tr.tournament_id,t.name tournament_name,tr.player_id,p.full_name,tr.final_rank,tr.score,tr.games_played,tr.wins,tr.draws,tr.losses,
       tr.rating_standard,tr.rating_rapid,tr.rating_blitz,tr.rating_used,tr.points_awarded,tr.calculated_at
from public.tournament_results tr join public.tournaments t on t.id=tr.tournament_id join public.players p on p.id=tr.player_id join public.seasons s on s.id=t.season_id where s.code='DGP-2027';

alter table public.seasons enable row level security;
alter table public.player_memberships enable row level security;
alter table public.user_profiles enable row level security;
alter table public.tournament_results enable row level security;
alter table public.scoring_rules enable row level security;
alter table public.scoring_rule_parameters enable row level security;
alter table public.scoring_position_points enable row level security;
alter table public.scoring_factor_values enable row level security;
alter table public.scoring_categories enable row level security;
alter table public.scoring_category_rules enable row level security;
alter table public.scoring_category_sources enable row level security;
alter table public.grand_prix_final_qualifiers enable row level security;
alter table public.junior_gp_final_qualifiers enable row level security;

-- Bootstrap policy: authenticated users can read operational DGP data;
-- write access is performed through SECURITY DEFINER admin RPCs.
create policy if not exists seasons_read_authenticated on public.seasons for select to authenticated using (true);
create policy if not exists tournament_results_read_authenticated on public.tournament_results for select to authenticated using (true);
create policy if not exists final_qualifiers_read_authenticated on public.grand_prix_final_qualifiers for select to authenticated using (true);
create policy if not exists junior_final_qualifiers_read_authenticated on public.junior_gp_final_qualifiers for select to authenticated using (true);

revoke all on function public.calculate_dgp_points(integer) from public;
revoke all on function public.update_dgp_result(bigint,integer,numeric,integer,integer,integer,integer) from public;
revoke all on function public.require_dgp_admin() from public;
grant execute on function public.calculate_dgp_points(integer) to authenticated;
grant execute on function public.update_dgp_result(bigint,integer,numeric,integer,integer,integer,integer) to authenticated;
